---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
        - name: backend
          image: nginx:1.25-alpine
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: dev-database-rds-conn
                  key: endpoint
                  optional: true
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "appdb"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: dev-database-rds-conn
                  key: username
                  optional: true
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-database-rds-conn
                  key: password
                  optional: true
            - name: ENVIRONMENT
              value: "dev"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
