---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: backend
  managed-by: argocd
  
configMapGenerator:
  - name: backend-config
    literals:
      - APP_NAME=backend
      - LOG_LEVEL=info

images:
  - name: nginx
    newTag: 1.25-alpine
